version: "3.8"
services:
  mongo:
    image: mongo:6.0.7-jammy
    environment:
      MONGO_INITDB_ROOT_USERNAME: easylearnz
      MONGO_INITDB_ROOT_PASSWORD: easylearnz
    volumes:
      - mongo_data:/data/db
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express:1.0.2-20-alpine3.19
    ports:
      - 8081:8081
    depends_on:
     - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: easylearnz
      ME_CONFIG_MONGODB_ADMINPASSWORD: easylearnz
      ME_CONFIG_MONGODB_URL: mongodb://easylearnz:easylearnz@mongo:27017/
volumes:
  mongo_data:
